export const RouteEnum = {
  LOGIN: '/login',
  REGISTER: '/register',
  HOME: '/home',
  PRODUCTS: '/products',
  PRODUCTS_DETAIL: '/products/:slug',
  ABOUT: '/about',
  CONTACT_US: '/contact-us',
  BLOG: '/blog',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ACCOUNT: '/account',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_PRODUCTS_ADD: '/admin/products/add',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_DISTRIBUTORS: '/admin/distributors',
};
